In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import roc_curve, roc_auc_score, confusion_matrix, accuracy_score, f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report


encoded_data = pd.read_csv('jamesstein_encoded.csv')
train_encoded_data, test_encoded_data, train_labels, test_labels = train_test_split(encoded_data, encoded_data['target'], test_size=0.3, random_state=42)


param_grid = [{'n_estimators': [10, 100, 500],
                  'min_samples_leaf': [1, 5, 10],
                  'random_state': [10, 100, 200]}]

scores = ['precision', 'recall']

for score in scores:
    print("# Tuning hyper-parameters for %s" % score)
    print()

    clf = GridSearchCV(RandomForestClassifier(), param_grid, scoring='%s_macro' % score, cv=5 )
    clf.fit(train_encoded_data, train_labels)

    print("Best parameters set found on development set:")
    print()
    print(clf.best_params_)
    print()
    print("Grid scores on development set:")
    print()
    means = clf.cv_results_['mean_test_score']
    stds = clf.cv_results_['std_test_score']
    for mean, std, params in zip(means, stds, clf.cv_results_['params']):
        print("%0.3f (+/-%0.03f) for %r"
              % (mean, std * 2, params))
    print()

    print("Detailed classification report:")
    print()
    print("The model is trained on the full development set.")
    print("The scores are computed on the full evaluation set.")
    print()
    y_true, y_pred = test_labels, clf.predict(train_encoded_data)
    print(classification_report(y_true, y_pred))
    print()
    
    from sklearn.neural_network import MLPClassifier





# Tuning hyper-parameters for precision



D:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedM

D:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedM

D:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedM

D:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedM

Best parameters set found on development set:

{'min_samples_leaf': 1, 'n_estimators': 500, 'random_state': 200}

Grid scores on development set:

0.722 (+/-0.203) for {'min_samples_leaf': 1, 'n_estimators': 10, 'random_state': 10}
0.777 (+/-0.246) for {'min_samples_leaf': 1, 'n_estimators': 10, 'random_state': 100}
0.787 (+/-0.197) for {'min_samples_leaf': 1, 'n_estimators': 10, 'random_state': 200}
0.799 (+/-0.237) for {'min_samples_leaf': 1, 'n_estimators': 100, 'random_state': 10}
0.807 (+/-0.163) for {'min_samples_leaf': 1, 'n_estimators': 100, 'random_state': 100}
0.818 (+/-0.157) for {'min_samples_leaf': 1, 'n_estimators': 100, 'random_state': 200}
0.807 (+/-0.163) for {'min_samples_leaf': 1, 'n_estimators': 500, 'random_state': 10}
0.814 (+/-0.160) for {'min_samples_leaf': 1, 'n_estimators': 500, 'random_state': 100}
0.842 (+/-0.122) for {'min_samples_leaf': 1, 'n_estimators': 500, 'random_state': 200}
0.475 (+/-0.198) for {'min_samples_leaf': 5, 'n_estimators': 10, 'random_sta

ValueError: Found input variables with inconsistent numbers of samples: [82, 189]

In [2]:
encoded_data = pd.read_csv('jamesstein_encoded.csv')
train_encoded_data, test_encoded_data, train_labels, test_labels = train_test_split(encoded_data, encoded_data['target'], test_size=0.3, random_state=42)


rf_model = RandomForestClassifier(n_estimators=500, criterion='gini', max_depth=None, min_samples_split=2,
                                  min_samples_leaf=1,
                                  min_weight_fraction_leaf=0.0, max_features='sqrt', max_leaf_nodes=None,
                                  min_impurity_decrease=0.0,
                                  bootstrap=True, oob_score=False, n_jobs=None, random_state=200, verbose=0,
                                  warm_start=False,
                                  class_weight=None, ccp_alpha=0.0, max_samples=None)
# 训练模型
rf_model.fit(train_encoded_data, train_labels)
# 评价模型
y_test_predict = rf_model.predict(test_encoded_data)
y_train_predict = rf_model.predict(train_encoded_data)

cfm = confusion_matrix(test_labels, y_test_predict)
print(cfm)


[[20  0  0  0  0  0  0  0]
 [ 0 22  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0]
 [ 0  0  0  1  3  0  0  0]
 [ 0  0  0  0  2  8  0  0]
 [ 0  0  0  0  1  0  6  0]
 [ 0  0  0  0  0  0  0  3]]


In [3]:
from sklearn.metrics import roc_auc_score
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.preprocessing import label_binarize

encoded_data= pd.read_csv('jamesstein_encoded.csv')
n_class = encoded_data.target
train_encoded_data, test_encoded_data, train_labels, test_labels = train_test_split(encoded_data, encoded_data['target'], test_size=0.3, random_state=42)

y_one_hot = label_binarize(test_labels, np.arange(n_class))

clf = RandomForestClassifier(n_estimators=500, criterion='gini', max_depth=None, min_samples_split=2,
                                  min_samples_leaf=1,
                                  min_weight_fraction_leaf=0.0, max_features='sqrt', max_leaf_nodes=None,
                                  min_impurity_decrease=0.0,
                                  bootstrap=True, oob_score=False, n_jobs=None, random_state=200, verbose=0,
                                  warm_start=False,
                                  class_weight=None, ccp_alpha=0.0, max_samples=None)
    # 训练模型
clf.fit(train_encoded_data, train_labels)

# 评价模型
y_test_predict = clf.predict(test_encoded_data)
y_train_predict = clf.predict(train_encoded_data)
    
y_score = clf.predict_proba(train_encoded_data)


metrics.roc_auc_score(y_one_hot, y_score, average='micro')   

#首先将矩阵y_one_hot和y_score展开，然后计算假正例率FPR和真正例率TPR
fpr, tpr, thresholds = metrics.roc_curve(y_one_hot.ravel(),y_score.ravel())
auc = metrics.auc(fpr, tpr)    

auc    
    
    
mpl.rcParams['font.sans-serif'] = u'SimHei'
mpl.rcParams['axes.unicode_minus'] = False
    
#FPR就是横坐标,TPR就是纵坐标
plt.plot(fpr, tpr, c = 'r', lw = 2, alpha = 0.7, label = u'AUC=%.3f' % auc)
plt.plot((0, 1), (0, 1), c = '#808080', lw = 1, ls = '--', alpha = 0.7)
plt.xlim((-0.01, 1.02))
plt.ylim((-0.01, 1.02))
plt.xticks(np.arange(0, 1.1, 0.1))
plt.yticks(np.arange(0, 1.1, 0.1))
plt.xlabel('False Positive Rate', fontsize=13)
plt.ylabel('True Positive Rate', fontsize=13)
plt.grid(b=True, ls=':')
plt.legend(loc='lower right', fancybox=True, framealpha=0.8, fontsize=12)
plt.title(u'酱卤肉数据RandomForest分类后的ROC和AUC', fontsize=17)
plt.show()



ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().